version: '3.8'

services:
  bus-casa-pwa:
    build: .
    container_name: bus-casa-pwa
    restart: unless-stopped
    ports:
      - "8091:80"
    networks:
      - bus-casa-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Europe/Madrid

networks:
  bus-casa-network:
    driver: bridge
